name: build


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:

      - uses: actions/checkout@v2
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: mkdir
        run: mkdir -p ./dist
      - name: build
        run: go build -v -o dist/ ./...
      - uses: actions/upload-artifact@v1
        with:
          name: bibfmt
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: main-ubuntu-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-macos-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-windows-latest
      - uses: actions/download-artifact@v1
        with:
          name: main-windows-latest
